# Site settings
title: Math.random()
header-img: img/home-bg.jpg
email: ggrau@me.com
copyright_name: Guillermo Grau Panea
description: "Random thoughts on software development and engineering"
baseurl: ""
url: "https://guigrpa.github.io"
twitter_username: guiroppa
github_username:  guigrpa
# facebook_username: 
email_username:  ggrau@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
