# Site settings
title: Math.random()
header-img: img/03.jpg
email: ggrau@me.com
copyright_name: Guillermo Grau Panea
description: Random thoughts on software development and engineering
baseurl: ""
url: https://guigrpa.github.io
twitter_username: guiroppa
github_username:  guigrpa
# facebook_username: 
# medium_username:
linkedin_username:  guillermograu
email_username:  ggrau@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: 
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - private

gems: 
  - jekyll-paginate
  - jekyll-feed
